# Generated by Django 4.2.2 on 2023-06-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('BEG', 'Beginner'), ('MID', 'Intermidiate'), ('EXP', 'Advanced')], default='BEG', max_length=3)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
    ]
